name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, windows, linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and package
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o marmounter_${{ matrix.os }}_${{ matrix.arch }} ./marmounter
      
      - name: Rename (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mv marmounter_${{ matrix.os }}_${{ matrix.arch }} marmounter_${{ matrix.os }}_${{ matrix.arch }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: marmounter_${{ matrix.os }}_${{ matrix.arch }}
          path: marmounter_${{ matrix.os }}_${{ matrix.arch }}*
