name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build_go:
    runs-on: macOS-latest
    strategy:
      matrix:
        os: [windows]
        arch: [amd64, arm64]
        # include:
        #   - os: darwin
        #     arch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Install macFUSE
        if: matrix.os == 'darwin'
        run: |
          brew install --cask macfuse

      - name: Install protoc
        run: |
          brew install protobuf
          protoc --version
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.32.0

      - name: Make protobuf files
        run: |
          make

      - name: Download dependencies
        run: |
          go mod download

      - name: Build and package
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o marmounter_${{ matrix.os }}_${{ matrix.arch }} ./marmounter
      
      - name: Rename (Windows)
        if: matrix.os == 'windows'
        run: |
          mv marmounter_${{ matrix.os }}_${{ matrix.arch }} marmounter_${{ matrix.os }}_${{ matrix.arch }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: marmounter_${{ matrix.os }}_${{ matrix.arch }}
          path: marmounter_${{ matrix.os }}_${{ matrix.arch }}*
